# Start with naming our workflow
name: Hello

on: 
  push: 
    branches: [main]
jobs:
  greet: 
    runs-on: ubuntu-latest
    steps:
       - name: Say Hello 
         run: echo "Hello Friends"
    repo-name:
    needs: greet
    runs-on: ubuntu-latest
    steps:
      - name: Show Repository Name
        run: echo "The Repo Name is ${{ github.event.repository.name }}"
